export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_FILTERED = 'SET_COMMENTS_FILTERED';
export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER';
export const INIT_COMMENTS = 'INIT_COMMENTS';
